# Generated by Django 3.1.2 on 2021-11-19 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Should not contain number', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Should not contain number', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats 12345', regex='^[0-9]{5}$')]),
        ),
    ]
